NETWORK=kaki
IMAGE=kaki-kafka
IMAGE_VERSION=0.0.1
CONTAINER=kafka
HOST=$CONTAINER

KFK_PORT=9092

ZK_HOST=zookeeper
ZK_CONTAINER=zookeeper

BLUEMIX_CONTAINER_MEMORY=128
REGISTRY=registry.ng.bluemix.net/mynodeappbue
BLUEMIX_IMG=$REGISTRY/$IMAGE