#!/bin/sh

echo "running startup...."

KAFKA_CONTAINER=kafka
KAFKA_IMG=spotify/kafka
KAFKA_PORT=9092
ZOOKEEPER_PORT=2181



docker run -h $KAFKA_CONTAINER -d --name $KAFKA_CONTAINER -p $ZOOKEEPER_PORT:$ZOOKEEPER_PORT -p $KAFKA_PORT:$KAFKA_PORT --env AUTO_CREATE_TOPICS=true  $KAFKA_IMG