HOST=kafka
IMG=kafka
CONTAINER=kafka
KAFKA_PORT=9092
ZOOKEEPER_PORT=2181
REGISTRY=registry.ng.bluemix.net/mynodeappbue

SRC_IMG=spotify/kafka
BLUEMIX_IMG=$REGISTRY/$IMG
BLUEMIX_CONTAINER_MEMORY=128
IP=169.44.6.146
